import sys
from pathlib import Path
import pandas as pd

# Add qsec-client directory to Python path
sys.path.append(str(Path('.').resolve() / 'qsec-client'))
from qsec_client.sample_code import Region, prepare_targets_file, upload_targets_file

def main():
    # Credentials and Configuration
    USERNAME = "q4615"
    GROUP_ID = "IND22"
    PRIVATE_KEY_PATH = Path("ind22_id_rsa.asc")
    SFTP_HOST = "sftp.qrt.cloud"
    REGION = Region.AMER

    # 1. Load the raw targets CSV generated by generate_submission.py
    raw_csv = Path("qrt_academy_IND22_20260528-1809.csv")
    if not raw_csv.exists():
        print(f"Error: {raw_csv} not found. Run generate_submission.py first.")
        return

    targets_df = pd.read_csv(raw_csv)
    print(f"Loaded {len(targets_df)} positions from {raw_csv}")
    print(f"  GMV: ${targets_df['target_notional'].abs().sum():,.0f}")
    print(f"  Net: ${targets_df['target_notional'].sum():,.2f}")

    # 2. Use QRT's prepare_targets_file to format the CSV properly
    print("\nPreparing targets file with QRT schema...")
    output_dir = Path(".")
    formatted_csv = prepare_targets_file(
        targets=targets_df,
        group_id=GROUP_ID,
        region=REGION,
        output_dir=output_dir,
    )
    print(f"  Formatted file: {formatted_csv}")

    # 3. Upload via SFTP
    print(f"\nUploading to {SFTP_HOST} as {USERNAME}...")
    try:
        upload_targets_file(
            targets_csv_path=formatted_csv,
            region=REGION,
            sftp_username=USERNAME,
            private_key_path=PRIVATE_KEY_PATH,
            sftp_host=SFTP_HOST,
        )
        print("\nSubmission successful!")
    except Exception as e:
        print(f"\nUpload failed: {e}")

if __name__ == "__main__":
    main()
